server:
  port: 8001

mybatis:
  type-aliases-package: com.wz.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?userUnicode-true&characterEncoding=utf-8
    username: root
    password: 123456

#注册到eureka
eureka:
  client:
    service-url:
      #单机
      #defaultZone: http://localhost:7001/eureka/
      #集群
      defaultZone: http://eureka700.com:7001/eureka/,http://eureka7001.com:7003/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: springcloud-provider-dept8001 #修改euerka上的默认描述

info:
  app.name: wz-springcloud
  company.name: wzpy.com