server:
  port: 7003


#Eureke配置
eureka:
  instance:
    hostname: eureka7002 #Eureke配置服务端的实例名称
  client:
    register-with-eureka: false #是否向eureke注册自己
    fetch-registry: false #便是自己注册中心
    service-url: #监控页面
      #单机
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/